// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dartp
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5af0IyatDwTtIiNlRw-xZJ8jeLHkkNuY',
    appId: '1:572646008850:web:58816808ee97340984d0cb',
    messagingSenderId: '572646008850',
    projectId: 'bekart-35dcf',
    authDomain: 'bekart-35dcf.firebaseapp.com',
    storageBucket: 'bekart-35dcf.appspot.com',
    measurementId: 'G-PMRNPR7JV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1a1w6ETw-rILcF9IVk8diX7cZApz_n4k',
    appId: '1:572646008850:android:613ae3c481a7df5d84d0cb',
    messagingSenderId: '572646008850',
    projectId: 'bekart-35dcf',
    storageBucket: 'bekart-35dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7uEiAWZ2hcLkAwnI2txeqpP_3sl8pe4',
    appId: '1:572646008850:ios:732ae5802bdda22584d0cb',
    messagingSenderId: '572646008850',
    projectId: 'bekart-35dcf',
    storageBucket: 'bekart-35dcf.appspot.com',
    iosBundleId: 'com.example.bekart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG7uEiAWZ2hcLkAwnI2txeqpP_3sl8pe4',
    appId: '1:572646008850:ios:732ae5802bdda22584d0cb',
    messagingSenderId: '572646008850',
    projectId: 'bekart-35dcf',
    storageBucket: 'bekart-35dcf.appspot.com',
    iosBundleId: 'com.example.bekart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5af0IyatDwTtIiNlRw-xZJ8jeLHkkNuY',
    appId: '1:572646008850:web:2da7fcd6080a135084d0cb',
    messagingSenderId: '572646008850',
    projectId: 'bekart-35dcf',
    authDomain: 'bekart-35dcf.firebaseapp.com',
    storageBucket: 'bekart-35dcf.appspot.com',
    measurementId: 'G-LP2T4V8M19',
  );
}
